require:
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Metrics/AbcSize:
  Max: 21
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
