version: '3'

services:

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: subscriptions_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis: 
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  postgres_data:
