name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.3.1'

  #     - name: Install dependencies
  #       run: |
  #         gem install bundler
  #         bundle install

  #     - name: Run RuboCop
  #       run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    # needs: lint
    env:
      TG_TOKEN: DDDDDDDDDDDDDD_xxxxxxxxxxxx_7pQ
      TG_URL: https://api.telegram.org/bot1111111111:DDDDDDDDDDDDDD_xxxxxxxxxxxx_7pQ
      TG_BOT_ID: 1111111111
      WEBHOOK_URL: https://webhookurl.app/
      WEBHOOK_ENDPOINT: AAAAABBBBBB
      WEBHOOK_SECRET_TOKEN: xxxxxxxxxxxxx
      REDIS_URL: redis://localhost:6379
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1

      - name: Start services via docker-compose
        run: docker-compose up -d redis

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            if docker-compose exec -T redis redis-cli ping | grep PONG; then
              echo "Redis is up!"
              break
            fi
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run RSpec
        run: bundle exec rspec
