name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      TG_TOKEN: DDDDDDDDDDDDDD_xxxxxxxxxxxx_7pQ
      TG_URL: https://api.telegram.org/bot1111111111:DDDDDDDDDDDDDD_xxxxxxxxxxxx_7pQ
      TG_BOT_ID: 1111111111
      WEBHOOK_URL: https://webhookurl.app/
      WEBHOOK_ENDPOINT: AAAAABBBBBB
      WEBHOOK_SECRET_TOKEN: xxxxxxxxxxxxx
      REDIS_URL: redis://localhost:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RSpec
        run: bundle exec rspec
